export const HUB_LAYERS = {
  ground: "ground",
  detail: "ground-detail",
  props: "props",
  overhead: "overhead",
  collision: "collision",
  markers: "markers",
} as const;

export const HUB_TILESET = {
  name: "hub",
  image: "tiles.png",
  tileSize: 16,
  columns: 16,
  rows: 8,
  width: 256,
  height: 128,
  tileCount: 128,
  gid: {
    grass: 1,
    grassTuft: 2,
    grassFlowersYellow: 3,
    grassFlowersWhite: 4,
    grassLight: 5,
    stoneCenterA: 9,
    stoneCenterB: 10,
    stoneCenterC: 11,
    stoneEdgeN: 12,
    stoneEdgeE: 13,
    stoneEdgeS: 14,
    stoneEdgeW: 15,
    stoneCorner: 16,
    waterA: 33,
    waterB: 34,
    waterEdgeN: 35,
    waterEdgeE: 36,
    waterEdgeS: 37,
    waterEdgeW: 38,
    waterCorner: 39,
    waterCornerNE: 40,
    waterCornerSW: 41,
    waterCornerSE: 42,
    shrub: 49,
    hedge: 50,
    treeTrunk: 51,
    treeCanopyLeft: 65,
    treeCanopyCenter: 66,
    treeCanopyRight: 67,
    treeCanopyLowerLeft: 68,
    treeCanopyLowerCenter: 69,
    treeCanopyLowerRight: 70,
    fenceHorizontal: 81,
    fenceVertical: 82,
    fencePost: 83,
    rock: 84,
    flowerOrange: 85,
    flowerBlue: 86,
    torchA: 97,
    torchB: 98,
    torchC: 99,
    lantern: 100,
  },
} as const;
