import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const outputPath = path.join(root, "packages/chain/src/generated/abi.ts");
const contracts = {
  BossHook: "bossPoolHookAbi",
  BossRouter: "bossRouterAbi",
  BossHP: "bossHpAbi",
  RoyToken: "royTokenAbi",
  MockUSD: "mockUsdAbi",
  BossCollectibles: "bossCollectiblesAbi",
} as const;
const artifactNames = Object.keys(contracts) as (keyof typeof contracts)[];

async function main() {
  const abis = await Promise.all(artifactNames.map(async (name) => {
    const artifactPath = path.join(root, `contracts/out/${name}.sol/${name}.json`);
    let artifact: { abi?: unknown };
    try {
      artifact = JSON.parse(await readFile(artifactPath, "utf8"));
    } catch (error) {
      throw new Error(`Cannot read ${artifactPath}. Run “bun run contracts:build” first.`, { cause: error });
    }
    if (!Array.isArray(artifact.abi)) throw new Error(`${artifactPath} has no compiled ABI.`);
    return [name, artifact.abi] as const;
  }));

  const source = [
    "// Generated by `bun run abi:export` from Foundry artifacts. Do not edit.",
    ...abis.map(([name, abi]) => `export const ${contracts[name]} = ${JSON.stringify(abi, null, 2)} as const;`),
    "",
  ].join("\n\n");

  if (process.argv.includes("--check")) {
    let current: string;
    try {
      current = await readFile(outputPath, "utf8");
    } catch {
      throw new Error("Generated ABI is missing. Run `bun run abi:export` and commit the result.");
    }
    if (current !== source) throw new Error("Generated ABI is stale. Run `bun run abi:export` and commit the result.");
    console.log("Generated ABIs match the current Foundry artifacts.");
    return;
  }

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, source);
  console.log(`Exported ${artifactNames.join(" and ")} ABIs to ${path.relative(root, outputPath)}.`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
