import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const outputPath = path.join(root, "packages/chain/src/generated/abi.ts");
const bytecodePath = path.join(root, "packages/chain/src/generated/bytecode.ts");
const contracts = {
  BossFactory: "bossFactoryAbi",
  BossHook: "bossPoolHookAbi",
  BossRouter: "bossRouterAbi",
  BossHP: "bossHpAbi",
  RoyToken: "royTokenAbi",
  MockUSD: "mockUsdAbi",
  BossCollectibles: "bossCollectiblesAbi",
} as const;
const bytecodes = {
  BossRouter: "bossRouterCreationCode",
  BossHook: "bossHookCreationCode",
} as const;
const artifactNames = Object.keys(contracts) as (keyof typeof contracts)[];

async function main() {
  const artifacts = await Promise.all(artifactNames.map(async (name) => {
    const artifactPath = path.join(root, `contracts/out/${name}.sol/${name}.json`);
    let artifact: { abi?: unknown; bytecode?: { object?: unknown; linkReferences?: unknown } };
    try {
      artifact = JSON.parse(await readFile(artifactPath, "utf8"));
    } catch (error) {
      throw new Error(`Cannot read ${artifactPath}. Run “bun run contracts:build” first.`, { cause: error });
    }
    if (!Array.isArray(artifact.abi)) throw new Error(`${artifactPath} has no compiled ABI.`);
    return [name, artifact] as const;
  }));

  const source = [
    "// Generated by `bun run abi:export` from Foundry artifacts. Do not edit.",
    ...artifacts.map(([name, artifact]) => `export const ${contracts[name]} = ${JSON.stringify(artifact.abi, null, 2)} as const;`),
  ].join("\n\n") + "\n";
  const bytecodeSource = [
    "// Generated by `bun run abi:export` from Foundry artifacts. Do not edit.",
    ...Object.entries(bytecodes).map(([name, exportName]) => {
      const artifact = artifacts.find(([artifactName]) => artifactName === name)?.[1];
      const object = artifact?.bytecode?.object;
      if (typeof object !== "string" || !object || /__\$[\da-f]{34}\$__/i.test(object)) {
        throw new Error(`Foundry artifact ${name} has missing or linked creation bytecode.`);
      }
      return `export const ${exportName} = ${JSON.stringify(object.startsWith("0x") ? object : `0x${object}`)} as const;`;
    }),
  ].join("\n\n") + "\n";

  if (process.argv.includes("--check")) {
    let currentAbi: string;
    let currentBytecode: string;
    try {
      [currentAbi, currentBytecode] = await Promise.all([
        readFile(outputPath, "utf8"),
        readFile(bytecodePath, "utf8"),
      ]);
    } catch {
      throw new Error("Generated ABI or bytecode is missing. Run `bun run abi:export` and commit the result.");
    }
    if (currentAbi !== source || currentBytecode !== bytecodeSource) {
      throw new Error("Generated ABI or bytecode is stale. Run `bun run abi:export` and commit the result.");
    }
    console.log("Generated ABIs and launch bytecode match the current Foundry artifacts.");
    return;
  }

  await mkdir(path.dirname(outputPath), { recursive: true });
  await Promise.all([writeFile(outputPath, source), writeFile(bytecodePath, bytecodeSource)]);
  console.log(`Exported ABIs and launch bytecode from ${artifactNames.join(", ")} into ${path.relative(root, path.dirname(outputPath))}.`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
